# Visit https://github.com/lowlighter/metrics#-documentation for full reference
name: Metrics
on:
  # Schedule updates (each hour)
  schedule: [{ cron: "0 * * * *" }]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: { branches: ["main"] }
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: 📊 Base
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: metrics-base.svg
          user: xyhhx
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: America/New_York
          plugin_fortune: yes

      - name: 📊 Achievements
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: xyhhx
          template: classic
          base: ""
          config_timezone: America/New_York
          filename: metrics-achievements.svg
          plugin_achievements: yes
          plugin_achievements_display: detailed

      - name: 📊 Coding habits etc
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: xyhhx
          template: classic
          base: ""
          config_timezone: America/New_York
          filename: metrics-habits.svg
          plugin_notable: yes
          plugin_habits: yes
          plugin_habits_charts_type: classic
          plugin_habits_days: 14
          plugin_habits_facts: yes
          plugin_habits_from: 200
          plugin_habits_languages_limit: 8
          plugin_habits_languages_threshold: 0%
          plugin_languages: yes
          plugin_languages_analysis_timeout: 15
          plugin_languages_analysis_timeout_repositories: 7.5
          plugin_languages_categories: markup, programming
          plugin_languages_colors: github
          plugin_languages_indepth: yes
          plugin_languages_limit: 8
          plugin_languages_other: yes
          plugin_languages_recent_categories: markup, programming
          plugin_languages_recent_days: 14
          plugin_languages_recent_load: 300
          plugin_languages_sections: most-used
          plugin_languages_threshold: 0%
          plugin_lines: yes
          plugin_lines_history_limit: 1
          plugin_lines_repositories_limit: 4
          plugin_lines_sections: base

      - name: 📊 Topics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: xyhhx
          template: classic
          base: ""
          config_timezone: America/New_York
          filename: metrics-topics.svg
          plugin_topics: yes
          plugin_topics_limit: 50
          plugin_topics_mode: mastered
          plugin_topics_sort: stars

      - name: 📊 Star lists
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}

          user: xyhhx
          template: classic
          base: ""
          config_timezone: America/New_York
          filename: metrics-starlists.svg
          plugin_starlists: yes
          plugin_starlists_languages: yes
          plugin_people: yes
          plugin_people_limit: 28
          plugin_people_size: 28
          plugin_people_types: followers, following

      - name: 📊 Social
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}

          user: xyhhx
          template: classic
          base: ""
          config_timezone: America/New_York
          filename: metrics-social.svg
          plugin_reactions: yes
          plugin_reactions_display: absolute
          plugin_reactions_ignored: github-actions[bot], dependabot[bot]
          plugin_reactions_limit: 200
          plugin_stackoverflow: yes
          plugin_stackoverflow_sections: ""
          plugin_stackoverflow_user: 1007638
          repositories_forks: yes
